feat: add-homepage
GuiBibeau/akeru pull request #54
Opened 2024-04-12 14:01 UTC by tobySolutions

## Description of the pull request

## Changes made

- Change 1
- Change 2
- ....

## Related issues

## Testings done

## Screenshots (if any)

## Checklist

- [ ] I have written tests
- [x] My code does not produce new errors
- [x] I gave myself a code review before asking others.

2024-04-12 22:01 UTC, GuiBibeau requested changes
Really beautiful first touch! I would prefer that we stay away from hard coded style values as much as possible in tailwind in favour of using the base style system they provide. 

For example:

mt-[20px] should become mt-5.

A quick tip to get those quickly is to use cmd+k in the tailwind docs:

https://tailwindcss.com/docs

2024-04-13 09:23 UTC, GuiBibeau commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +    console.log(data);
we can remove that console.log here

2024-04-13 09:24 UTC, tobySolutions commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +    console.log(data);
Ok, awesome.

2024-04-13 09:24 UTC, tobySolutions commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +    console.log(data);
All done.

2024-04-13 09:33 UTC, GuiBibeau reviewed
tiny more tweaks but great improvements!!

2024-04-13 09:33 UTC, GuiBibeau commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +      "https://sheet.best/api/sheets/6b8ad6e3-f87c-4649-b435-ef5a1051f4b3";
let's move this to a .env file that we gitignore and make sure we change the google sheet to avoid this one being in the public.

People will crawl github for those and attempt at messing around with data.

2024-04-13 09:33 UTC, GuiBibeau commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +    <form className="w-full" onSubmit={handleSubmit}>
could this have been a mutation in a server action to avoid exposing the URL to the google sheet?

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations

2024-04-13 09:33 UTC, GuiBibeau commented on packages/akeru-frontend/app/components/ui/drawer/Drawer.tsx
> +              <FaGithub className="w-5 h-5 cursor-pointer hover:text-[#3dff8b]" />
colours should probably be added to tailwind.config.js and be referenced by their name instead of the interpolated value:

https://tailwindcss.com/docs/configuration

2024-04-13 09:33 UTC, GuiBibeau commented on packages/akeru-frontend/app/components/ui/form/FormInput.tsx
> +    <div className="text-[#ffffff] bg-[#32323C] text-[14px] p-[8px]  w-full h-full tablet_max:text-[13px]">
```suggestion
<div className="text-white bg-gray-800 text-lg py-2 px-4 w-full h-full sm:text-sm">

```

2024-04-13 10:01 UTC, tobySolutions commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +      "https://sheet.best/api/sheets/6b8ad6e3-f87c-4649-b435-ef5a1051f4b3";
DONE!

2024-04-13 10:02 UTC, tobySolutions commented on packages/akeru-frontend/app/components/ui/form/Form.tsx
> +    <form className="w-full" onSubmit={handleSubmit}>
DONE!

2024-04-13 10:12 UTC, tobySolutions commented on packages/akeru-frontend/app/components/ui/drawer/Drawer.tsx
> +              <FaGithub className="w-5 h-5 cursor-pointer hover:text-[#3dff8b]" />
Done!

2024-04-14 11:51 UTC, GuiBibeau approved these changes
Well done! 🔥 🚀 

ship it! 🚢

2024-04-14 11:52 UTC, tobySolutions commented
> Well done! 🔥 🚀
> 
> ship it! 🚢

Yay!!!!!!!!!!

2024-04-14 11:54 UTC, merged